-- MySQL Script generated by MySQL Workbench
-- Thu Jun 17 01:03:41 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema carRental
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema carRental
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `carRental` DEFAULT CHARACTER SET utf8 ;
USE `carRental` ;

-- -----------------------------------------------------
-- Table `carRental`.`cars`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carRental`.`cars` (
  `CarId` INT NOT NULL AUTO_INCREMENT,
  `brand` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `year` INT NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `price` INT NOT NULL,
  `image` VARCHAR(45) NOT NULL,
  `isFree` TINYINT NOT NULL,
  `comfortClass` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`CarId`),
  UNIQUE INDEX `CarId_UNIQUE` (`CarId` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carRental`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carRental`.`users` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `secondName` VARCHAR(45) NOT NULL,
  `dateOfBirth` DATE NOT NULL,
  `phoneNumber` VARCHAR(16) NOT NULL,
  `login` VARCHAR(16) NOT NULL,
  `password` VARCHAR(16) NOT NULL,
  `isAdmin` TINYINT NOT NULL DEFAULT 0,
  `isManager` TINYINT NOT NULL DEFAULT 0,
  `passportSeries` VARCHAR(10) NULL,
  `passportNumber` VARCHAR(10) NULL,
  `isBanned` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`UserId`),
  UNIQUE INDEX `UserId_UNIQUE` (`UserId` ASC) VISIBLE,
  UNIQUE INDEX `phoneNumber_UNIQUE` (`phoneNumber` ASC) VISIBLE,
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `carRental`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `carRental`.`orders` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `isApproved` TINYINT NOT NULL,
  `users_UserId` INT NOT NULL,
  `cars_CarId` INT NOT NULL,
  `startTime` VARCHAR(50) NULL,
  `endTime` VARCHAR(50) NULL,
  `driver` TINYINT NOT NULL DEFAULT 0,
  `price` INT NOT NULL DEFAULT 0,
  `Comment` VARCHAR(200) NULL,
  `Fine` INT NULL,
  PRIMARY KEY (`orderId`),
  UNIQUE INDEX `orderId_UNIQUE` (`orderId` ASC) VISIBLE,
  INDEX `fk_orders_users_idx` (`users_UserId` ASC) VISIBLE,
  INDEX `fk_orders_cars1_idx` (`cars_CarId` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users`
    FOREIGN KEY (`users_UserId`)
    REFERENCES `carRental`.`users` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_cars1`
    FOREIGN KEY (`cars_CarId`)
    REFERENCES `carRental`.`cars` (`CarId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
